[package]
name = "heig-vd-summary"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Aubry Mangold <aubry.mangold@heig-vd.ch>"]
license = "MIT-0"
description = "A course summary template for HEIG-VD"
