[package]
name = "heig-vd-notes"
version = "1.1.0"
entrypoint = "lib.typ"
authors = ["Aubry Mangold <aubry.mangold@heig-vd.ch>"]
license = "MIT-0"
description = "Personal notes templates for HEIG-VD courses"
