[package]
name = "heig-vd-report"
version = "1.1.0"
entrypoint = "lib.typ"
authors = ["Aubry Mangold <aubry.mangold@heig-vd.ch>"]
license = "MIT-0"
description = "Report template for HEIG-VD courses"
